exports.AttributeDeclaration = require('./AttributeDeclaration').AttributeDeclaration;
exports.CategoryDeclaration = require('./CategoryDeclaration').CategoryDeclaration;
exports.ConcreteCategoryDeclaration = require('./ConcreteCategoryDeclaration').ConcreteCategoryDeclaration;
exports.ConcreteWidgetDeclaration = require('./ConcreteWidgetDeclaration').ConcreteWidgetDeclaration;
exports.DeclarationList = require('./DeclarationList').DeclarationList;
exports.AbstractMethodDeclaration = require('./AbstractMethodDeclaration').AbstractMethodDeclaration;
exports.ConcreteMethodDeclaration = require('./ConcreteMethodDeclaration').ConcreteMethodDeclaration;
exports.NativeMethodDeclaration = require('./NativeMethodDeclaration').NativeMethodDeclaration;
exports.TestMethodDeclaration = require('./TestMethodDeclaration').TestMethodDeclaration;
exports.EnumeratedCategoryDeclaration = require('./EnumeratedCategoryDeclaration').EnumeratedCategoryDeclaration;
exports.SingletonCategoryDeclaration = require('./SingletonCategoryDeclaration').SingletonCategoryDeclaration;
exports.NativeCategoryDeclaration = require('./NativeCategoryDeclaration').NativeCategoryDeclaration;
exports.NativeResourceDeclaration = require('./NativeResourceDeclaration').NativeResourceDeclaration;
exports.NativeWidgetDeclaration = require('./NativeWidgetDeclaration').NativeWidgetDeclaration;
exports.EnumeratedNativeDeclaration = require("./EnumeratedNativeDeclaration").EnumeratedNativeDeclaration;
exports.OperatorMethodDeclaration = require("./OperatorMethodDeclaration").OperatorMethodDeclaration;
exports.GetterMethodDeclaration = require("./GetterMethodDeclaration").GetterMethodDeclaration;
exports.SetterMethodDeclaration = require("./SetterMethodDeclaration").SetterMethodDeclaration;
exports.NativeGetterMethodDeclaration = require("./NativeGetterMethodDeclaration").NativeGetterMethodDeclaration;
exports.NativeSetterMethodDeclaration = require("./NativeSetterMethodDeclaration").NativeSetterMethodDeclaration;
exports.DispatchMethodDeclaration = require("./DispatchMethodDeclaration").DispatchMethodDeclaration;

require('./BaseMethodDeclaration').resolve();
require('./ConcreteCategoryDeclaration').resolve();
require('./DispatchMethodDeclaration').resolve();
