export {default as InlinedProcessor} from './InlinedProcessor.js'
export {default as PageWidgetOfProcessor} from './PageWidgetOfProcessor.js'
export {default as WidgetFieldProcessor} from './WidgetFieldProcessor.js'
export {default as WidgetPropertiesProcessor} from './WidgetPropertiesProcessor.js'
export {default as AnnotationProcessors} from './AnnotationProcessors.js'
